### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by greenbigfrog** [greenbigfrog/discordtipbot#30]
Add a statistic command that displays the amount of guilds the bot is in in a command called `stats`
[dcr](https://meew0.github.io/discordcr/doc/v0.1.0/Discord/REST.html#get_current_user_guilds-instance-method)
[discord](https://discordapp.com/developers/docs/resources/user#get-current-user-guilds)

**Comment by z64** [comment]
Since you're only running one shard right now, you can just count (`#size`) the number of guilds in the cache.

**Comment by greenbigfrog** [comment]
Right. Forget we received all guilds in READY and they would be in the cache...
