### ISSUE TITLE
Don't have people install a patched Crystal compiler

### ISSUE THREAD

**Issue by watzon** [greenbigfrog/discordtipbot#53]
The nice thing about Crystal is that you can modify the way primitives work without modifying the source code. Instead of having people use a special version of the Crystal compiler, just add modified versions of the standard lib to your own code and import them. This makes things a lot easier on those using your bot, and means you don't have to keep your crystal branch up to date all the time.

**Comment by greenbigfrog** [comment]
Thanks for commenting! Could you provide me with instructions how to do so?

(Also, the custom branch/version isn't required after the next release)

**Comment by z64** [comment]
This is what I was talking about [in my review](https://github.com/greenbigfrog/discordtipbot/pull/48#issuecomment-359523264) by simply monkey patching in the method fixes needed for the bot to function by reopening `BigDecimal`.

**Comment by greenbigfrog** [comment]
I'm not sure if watzon meant something else though

**Comment by watzon** [comment]
Yeah I don't know what you modified in the Crystal compiler, but if you modified or added methods to `BigDecimal` then all you'd have to do is:

```crystal
# src/core_extensions/big_decimal.cr
class BigDecimal
  # Make your modifications in here
end
```

```crystal
# src/discordtipbot.cr
require "./core_extensions/*"

# Other imports and code
```

Crystal classes and modules are overridable, so you don't actually have to modify the compiler to make changes. You could also just create your own class and extend BigDecimal.
