### ISSUE TITLE
Round amount per user in soak and rain

### ISSUE THREAD

**Issue by greenbigfrog** [greenbigfrog/discordtipbot#54]
![sth](https://cdn.discordapp.com/attachments/169518155008442369/405798042864975872/unknown.png)

**Comment by IncognitoJam** [comment]
Would converting the value to a BigDecimal be enough to fix this? It seems to handle formatting itself already.

So this:
`amount_each = amount / targets.size`

Would go to this:
`amount_each = BigDecimal.new(amount / targets.size)`

**Comment by greenbigfrog** [comment]
and after that round it. Look at `def amount`
