### ISSUE TITLE
small grammatical error

### ISSUE THREAD

**Issue by CreeperzEdge** [greenbigfrog/discordtipbot#9]
https://github.com/greenbigfrog/discordtipbot/blob/315e5ad89debea2df4a3498960808fdab7ef64a1/src/discordtipbot/discordbot.cr#L174
replace `a` with `an`

**Comment by IncognitoJam** [comment]
This should be fixed in my PR #10

**Comment by greenbigfrog** [comment]
Thanks for reporting. @IncognitoJam not sure if you have noticed it, but github shows reference's, when you mention an issue or PR in an other issue or PR. So no need to leave a comment, unless the person that merges a PR forgets to close the issue
